SELECT DISTINCT I.ITEM_ID, I.DESCRIPTION, I.CATEGORY
FROM ITEM I, ITEM T
WHERE I.CATEGORY = T.CATEGORY
AND I.ITEM_ID <> T.ITEM_ID
AND I.CATEGORY != 'DOG'
AND I.CATEGORY != 'HOR'
ORDER BY I.CATEGORY, ITEM_ID;