SELECT CUST_ID, FIRST_NAME, LAST_NAME
FROM CUSTOMER
WHERE CUST_ID IN (SELECT I.CUST_ID
                  FROM INVOICES AS I, INVOICE_LINE AS IL
		  WHERE IL.ITEM_ID = 'KH81'
		  AND I.INVOICE_NUM = IL.INVOICE_NUM);