SELECT SALES_REP.REP_ID, SALES_REP.FIRST_NAME, SALES_REP.LAST_NAME
FROM SALES_REP
WHERE SALES_REP.REP_ID IN (SELECT REP_ID
                           FROM CUSTOMER
                           WHERE CREDIT_LIMIT = 500.00);