SELECT INVOICE_NUM, INVOICE_DATE
FROM INVOICES
WHERE CUST_ID = '435'
UNION
SELECT I.INVOICE_NUM, I.INVOICE_DATE
FROM INVOICES I, INVOICE_LINE IL
WHERE I.INVOICE_NUM = IL.INVOICE_NUM
AND ITEM_ID = 'KH81';