SELECT SR.PROPERTY_ID, P.OFFICE_NUM, P.ADDRESS, SR.EST_HOURS, SR.SPENT_HOURS, P.OWNER_NUM, O.LAST_NAME
FROM SERVICE_REQUEST SR, PROPERTY P, OWNER O
WHERE O.OWNER_NUM = P.OWNER_NUM
AND SR.PROPERTY_ID = P.PROPERTY_ID;